# pykrete Homebrew formula — generated by the pykrete release workflow.
# Do not edit by hand; changes are overwritten on the next release.
class Pykrete < Formula
  desc "Static schema checking for PySpark dataframes"
  homepage "https://github.com/amirnaderi93/pykrete"
  version "0.1.31"
  license "MIT"

  base = "https://github.com/amirnaderi93/pykrete/releases/download/v#{version}"

  on_macos do
    on_arm do
      url "#{base}/pykrete-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "8078d9d00f5597d2db381a265e75e67786929850a36ed7abda8f695dfedbee24"
    end
    on_intel do
      url "#{base}/pykrete-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "3e9f238869fdd79041f94dcd0f65e6a620d36f04088742c249a0f700d0818d89"
    end
  end

  on_linux do
    on_intel do
      url "#{base}/pykrete-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "22e60abd0c55bde7bbfdb1768952e27db1291312158b59244b7d48246122a631"
    end
  end

  def install
    bin.install "pykrete"
    bin.install "pykrete-lsp"
  end

  test do
    assert_match "pykrete", shell_output("#{bin}/pykrete --help 2>&1")
  end
end
