# pykrete Homebrew formula — generated by the pykrete release workflow.
# Do not edit by hand; changes are overwritten on the next release.
class Pykrete < Formula
  desc "Static schema checking for PySpark dataframes"
  homepage "https://github.com/amirnaderi93/pykrete"
  version "0.1.3"
  license "MIT"

  base = "https://github.com/amirnaderi93/pykrete/releases/download/v#{version}"

  on_macos do
    on_arm do
      url "#{base}/pykrete-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "87f6b6d5708bce38389378a6a161e4bc4a34d68b50cf70bcc59e2cd936f29b24"
    end
    on_intel do
      url "#{base}/pykrete-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "d4c85cc36af3d216ec9638b1c6bbac5024438dbc9b4b52a602c9cafb649fce1a"
    end
  end

  on_linux do
    on_intel do
      url "#{base}/pykrete-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "bf71b36543f8c66235c53db3819ff2d1d0f7c4d572e5db214e27083d89f77d85"
    end
  end

  def install
    bin.install "pykrete"
    bin.install "pykrete-lsp"
  end

  test do
    assert_match "pykrete", shell_output("#{bin}/pykrete --help 2>&1")
  end
end
