# pykrete Homebrew formula — generated by the pykrete release workflow.
# Do not edit by hand; changes are overwritten on the next release.
class Pykrete < Formula
  desc "Static schema checking for PySpark dataframes"
  homepage "https://github.com/amirnaderi93/pykrete"
  version "0.1.1"
  license "MIT"

  base = "https://github.com/amirnaderi93/pykrete/releases/download/v#{version}"

  on_macos do
    on_arm do
      url "#{base}/pykrete-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "8c64291d9ee8fcd176a91be8fe692c0929b51c33f192ba9d4f17021fb5a97300"
    end
    on_intel do
      url "#{base}/pykrete-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "2f25e4282ec295fad17b470e63aff8fbad8da8d5a8b0bcc610b26d09ef1fe8c7"
    end
  end

  on_linux do
    on_intel do
      url "#{base}/pykrete-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "fa4dfd75e52d243187dd0c89a102d9966595be839a3fd6790f5d1a2f472a3fe0"
    end
  end

  def install
    bin.install "pykrete"
    bin.install "pykrete-lsp"
  end

  test do
    assert_match "pykrete", shell_output("#{bin}/pykrete --help 2>&1")
  end
end
